from os import environ, urandom
from logging import DEBUG, INFO, WARNING, ERROR, CRITICAL, NOTSET

__DEFAULT_LOG_LEVEL = environ.get("DEFAULT_LOG_LEVEL", "INFO").upper()
DEFAULT_LOG_LEVEL = NOTSET
if __DEFAULT_LOG_LEVEL == "DEBUG": DEFAULT_LOG_LEVEL = DEBUG
elif __DEFAULT_LOG_LEVEL == "INFO": DEFAULT_LOG_LEVEL = INFO
elif __DEFAULT_LOG_LEVEL == "WARNING": DEFAULT_LOG_LEVEL = WARNING
elif __DEFAULT_LOG_LEVEL == "ERROR": DEFAULT_LOG_LEVEL = ERROR
elif __DEFAULT_LOG_LEVEL == "CRITICAL": DEFAULT_LOG_LEVEL = CRITICAL
LOG_FILE_PATH = environ.get("LOG_FILE_PATH", None)

PATH_PREFIX = environ.get("PATH_PREFIX", "")

MONGO_CONNECTION_STRING = environ.get("MONGO_CONNECTION_STRING", "mongodb://root:example@localhost/admin")
